AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM-EB-v8

  Sample SAM Template for SAM-EB-v8
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  hwFnv8:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
        Trigger:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - custom.vue3sam-eb-analysis
              detail-type:
                - payment
              detail:
                action:
                  - sendcard

  eventBroadcastFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: event-broadcast/
      Handler: handler.lambdaHandler
      Runtime: nodejs20.x
      Events:
        eventBroadcast:
          Type: Api
          Properties:
            Path: /broadcast
            Method: get      
      Policies:
        - Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - events:PutEvents

  listener3HandlerFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: event-listen/
      Handler: listener3.listener3Handler
      Runtime: nodejs20.x
      Events:
        Trigger:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - custom.vue3sam-eb-analysis
              detail-type:
                - payment
              detail:
                result:
                  - anything-but: approved

  listener2HandlerFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: event-listen/
      Handler: listener2.listener2Handler
      Runtime: nodejs20.x
      Events:
        Trigger:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - custom.vue3sam-eb-analysis
              detail-type:
                - payment
              detail:
                location:
                  - prefix: NY-

  listener1HandlerFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: event-listen/
      Handler: listener1.listener1Handler
      Runtime: nodejs20.x

  listener1Rule:
    Type: AWS::Events::Rule
    Properties:
      Description: Approved transactions
      EventBusName: default
      EventPattern:
        source:
          - custom.vue3sam-eb-analysis
        detail-type:
          - payment
        detail:
          result:
            - approved
      State: ENABLED
      Targets:
        - Arn: !GetAtt listener1HandlerFn.Arn
          Id: listener1Target

  invokeLambdaEventListener1Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref listener1HandlerFn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt listener1Rule.Arn



# Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  # hwFnv8Api:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  # hwFnv8:
  #   Description: "Hello World Lambda Function ARN"
  #   Value: !GetAtt hwFnv8.Arn
  # hwFnv8IamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt hwFnv8Role.Arn
